examples/kind: Add timeout unit in config
helm3 requires the timeout value to have a unit.
Without this, the test results in the following error:

```
Error: invalid argument "800" for "--timeout" flag: time: missing unit in duration 800
```

Signed-off-by: Sunny <darkowlzz@protonmail.com>